dataset:
  class_name: "BinaryLabeledCOCODataset"
  attributes:
    image_directory_path: "resources/dataset/mixed_cars_and_coco/training/images"
    annotation_file_path: "resources/dataset/mixed_cars_and_coco/training/annotations/annotation.json"

loader:
  shuffle: True
  batch_size: 8

model:
  class_name: "DTJointStructureClassifier"
  attributes:
    probability_threshold: 0.50
    min_samples_split: 60
    max_depth: 4

run:
  device: "cuda"
  maximum_iterations: null
  part_detectors_model_file_name: "part_detectors_vgg16_layer_21_cdf_95"
  joint_structure_model_file_name: "joint_structure_decision_tree_classifier"
